config/routes.rb
OutilWeb::Application.routes.draw do

  devise_for :users
  root :to => "landing#index"

  devise_scope :user do
    get "/register" => "devise/registrations#new", :as =>:register
    get "/login" => "devise/sessions#new", :as => :login
  end

  get "api/publish"
  get "api/localize"
  get "api/authenticate"
  get "api/take"

  get "dashboard" => 'dashboard#index', :as => :dashboard

  get "login" => 'login#index'
  post "login/submit"

  get "profile/mine", :as => :profile
  get "profile/edit"
  get "profile/submit"
  get "users/:username" => 'profile#show'

  get "users/:username/:utilityname" => 'utility#show'
  get "users/:username/:utilityname/edit" => 'utility#edit'
  get "users/:username/:utilityname/submit" => 'utility#submit'
  get "users/:username/:utilityname/run" => 'utility#run'
  get "users/:username/:utilityname/assert" => 'utility#assert'
  get "users/:username/:utilityname/versions" => 'utility#versions'
end

app/models/assertion.rb
class Assertion < ActiveRecord::Base
    belongs_to :user
    belongs_to :version
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :version
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :comments
  has_many :versions
  has_many :assertions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/utility.rb
class Utility < ActiveRecord::Base
    has_many :versions
    has_many :assertions
    has_many :comments
end

app/models/version.rb
class Version < ActiveRecord::Base
    belongs_to :utility
    belongs_to :user
    has_many :comments
    has_many :assertions
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  # TODO
  # The data specificiation needs to get fleshed
  # out a bit more before the web interface
  # is ready to talk about this  

  def publish
    # client says "publish my localized utilities(s)"
  end

  def localize
    # client says "copy all my taken utilities to my local index"
  end

  def authenticate
    # client says "hey i am who i say i am"
  end

  def take
    # client says "hey i'd like to use this person's method"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
    @utilities = @user.versions
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

    def index
      if user_signed_in?
        redirect_to dashboard_url
      else
        render :index
      end
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!, :only => [:mine, :edit, :submit]

  def mine
    @user = current_user
    render "profile#show"
  end

  def edit
    @user = current_user
  end

  def submit
    unless params[:user]
      redirect_to "profile#edit"
    end
    @user = current_user
    unless @user.update(params[:user])
      redirect_to "profile#edit"
    else
      render action: :mine
    end
  end

  def show
    unless params[:username].present?
      redirect_to dashboard_url
    end
    @user = User.find_by_username(parms[:username])
    unless @user
      redirect_to dashboard_url
    end
  end

end

app/controllers/utility_controller.rb
class UtilityController < ApplicationController
  # TODO
  # The data specificiation needs to get fleshed
  # out a bit more before the web interface
  # is ready to talk about this  

  def show
    # display method details
  end

  def run
    # show method evaluated author-supplied assertions
  end

  def take
    # duplicates author-supplied version
    # creates a version attached to the user profile
    # version is attached to the utility parent
  end

  def edit
    # user can change 
    # - body
    # - description
    # - test arguments
    # - test assertions
    # - name
    # - arguments defaults
  end

  def assert
    # run with viewer-supplied arguments
  end

  def submit
    # update, post-edit
  end

  def versions
    # list variants on the utility name
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_github user
    "https://github.com/#{user.github}"
  end

  def format_stack_overflow user
    "http://stackoverflow.com/users/#{user.stack_overflow}"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/utility_helper.rb
module UtilityHelper
end

app/views/dashboard/_user_sidebar.html.erb
<div id='user-profile'>
  <div id='user-name'>
    <%= user.username %>
  </div>
  <div id='user-stats'>
    <div id='authored-count'>
    <%= 0 %> Methods Authored
    </div>
    <div id='taken-count'>
      <%= 0 %> Methods in Module
    </div>
  </div>
</div>

app/views/dashboard/_utility_list.html.erb
<div id='utility-list'>
  <h2>Your Utils</h1>
  <% utilities.each do |util| %>
    <%= render partial: 'dashboard/utility', locals: {utility: util} %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<%= render partial: 'shared/utility_list', locals: {utilities: @utilities} %>
<%= render partial: 'dashboard/user_sidebar', locals: {user: @user} %>

app/views/landing/index.html.erb
<ul>
  <li><%= link_to "Sign Up", register_path %></li>
  <li><%= link_to "Sign In", login_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outil Web</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= render partial: 'shared/header' %>
<%= yield %>

</body>
</html>

app/views/shared/_generic_profile_side.html.erb
<div class="profile-generic-sidebar">
  <div id='profile-username'>
    <%= user.username %> 
  </div>
  <div id='profile-real-name'>
    <%= user.name %> 
  </div>
  <div id='profile-email'>
    <%= link_to user.email, "mailto: #{user.email}" %> 
  </div>
  <div id='profile-website'>
    <%= link_to user.email, "mailto: #{user.email}" %> 
  </div>
  <div id='profile-github'>
    <%= link_to "Github", format_github(user) %> 
  </div>
  <div id='profile-stack-overflow'>
    <%= link_to "Stack Overflow", format_stack_overflow(user) %> 
  </div>
  
</div>

app/views/shared/_header.html.erb
<div id="nav-header">
  <div id="logo">
    <h1>
      Outil
    </h1>
  </div>
  <div id="nav-bar">
    <ul>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Your Profile", profile_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
    </ul>
  </div>
</div>

app/views/shared/_utility.html.erb
<div class='utility-box'>
  <h3>
    <%= utility.name %>
  </h3>
</div>

app/views/shared/_utility_list.html.erb
<div id='utility-list'>
  <h2>Your Utils</h1>
  <% utilities.each do |util| %>
    <%= render partial: 'shared/utility', locals: {utility: util} %>
  <% end %>
</div>

app/views/shared/_utility_list_with_buttons.html.erb
<div id='utility-list-with-buttons'>
  <% utilities.each do |util| %>
    <%= render partial: 'shared/utility_with_button', locals: {utility: util, user: @user} %>
  <% end %>
</div>

app/views/shared/_utility_with_button.html.erb
<div class='utility-box-with-buttons'>
  <div class='utility-name'>
    <%= link_to utility.name, url_for(:controller => :utility, :action => :show, :utilityname => utility.name, :username => user) %>
  </div>
  <div class='utility-description'>
    <%= utility.description %>
  </div>
  <div class='take-button'>
    <%= link_to "Take", url_for(:controller => :utility, :action => :take, :utilityname => utility.name, :username => user) %>
  </div>
</div>